import React from "react";

const LandingPage = () => {
  return <div>
    <h1>LandingPage</h1>
    <div className="flex flex-col gap-10">
      <section>Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda laudantium veniam illo qui labore provident sunt ipsum aliquid non ipsa. Repudiandae nisi accusamus assumenda iste iusto quos. Numquam impedit, animi dolor illo at atque facere. Deserunt inventore, ut ea natus fuga, nesciunt doloremque, totam quos amet nihil repellat culpa corporis! In tempore et distinctio doloremque at accusamus deserunt magnam. Libero dignissimos aut architecto tempora at corporis quas commodi praesentium minus, cum voluptate eum, labore nemo deserunt quibusdam rem perferendis tempore optio veniam. Quidem, maiores praesentium delectus eius numquam ipsa quibusdam eaque animi, veritatis consequuntur explicabo molestias, ut natus! Voluptatum excepturi consequuntur, dicta asperiores odio ipsum veniam, omnis quibusdam obcaecati, beatae enim velit incidunt saepe! Doloremque, ex labore? Doloribus ex inventore veniam harum cum quasi ipsam natus, dolorum debitis commodi labore repudiandae quos magnam necessitatibus iusto mollitia consequatur ullam optio dicta dolores! Asperiores quaerat, neque a voluptas aliquam sunt adipisci saepe eius ratione laborum commodi sed dignissimos dolore reiciendis dolores repellat aut rem! Iste, nisi nihil. Vero laboriosam nemo saepe, incidunt dolor reiciendis corrupti. Quibusdam officia doloribus distinctio necessitatibus harum hic odit nemo. Ratione, debitis aut eligendi cupiditate esse incidunt quasi possimus? Doloribus velit voluptatem inventore, totam officiis culpa quae commodi?</section>
      <section>Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda laudantium veniam illo qui labore provident sunt ipsum aliquid non ipsa. Repudiandae nisi accusamus assumenda iste iusto quos. Numquam impedit, animi dolor illo at atque facere. Deserunt inventore, ut ea natus fuga, nesciunt doloremque, totam quos amet nihil repellat culpa corporis! In tempore et distinctio doloremque at accusamus deserunt magnam. Libero dignissimos aut architecto tempora at corporis quas commodi praesentium minus, cum voluptate eum, labore nemo deserunt quibusdam rem perferendis tempore optio veniam. Quidem, maiores praesentium delectus eius numquam ipsa quibusdam eaque animi, veritatis consequuntur explicabo molestias, ut natus! Voluptatum excepturi consequuntur, dicta asperiores odio ipsum veniam, omnis quibusdam obcaecati, beatae enim velit incidunt saepe! Doloremque, ex labore? Doloribus ex inventore veniam harum cum quasi ipsam natus, dolorum debitis commodi labore repudiandae quos magnam necessitatibus iusto mollitia consequatur ullam optio dicta dolores! Asperiores quaerat, neque a voluptas aliquam sunt adipisci saepe eius ratione laborum commodi sed dignissimos dolore reiciendis dolores repellat aut rem! Iste, nisi nihil. Vero laboriosam nemo saepe, incidunt dolor reiciendis corrupti. Quibusdam officia doloribus distinctio necessitatibus harum hic odit nemo. Ratione, debitis aut eligendi cupiditate esse incidunt quasi possimus? Doloribus velit voluptatem inventore, totam officiis culpa quae commodi?</section>
      <section>Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda laudantium veniam illo qui labore provident sunt ipsum aliquid non ipsa. Repudiandae nisi accusamus assumenda iste iusto quos. Numquam impedit, animi dolor illo at atque facere. Deserunt inventore, ut ea natus fuga, nesciunt doloremque, totam quos amet nihil repellat culpa corporis! In tempore et distinctio doloremque at accusamus deserunt magnam. Libero dignissimos aut architecto tempora at corporis quas commodi praesentium minus, cum voluptate eum, labore nemo deserunt quibusdam rem perferendis tempore optio veniam. Quidem, maiores praesentium delectus eius numquam ipsa quibusdam eaque animi, veritatis consequuntur explicabo molestias, ut natus! Voluptatum excepturi consequuntur, dicta asperiores odio ipsum veniam, omnis quibusdam obcaecati, beatae enim velit incidunt saepe! Doloremque, ex labore? Doloribus ex inventore veniam harum cum quasi ipsam natus, dolorum debitis commodi labore repudiandae quos magnam necessitatibus iusto mollitia consequatur ullam optio dicta dolores! Asperiores quaerat, neque a voluptas aliquam sunt adipisci saepe eius ratione laborum commodi sed dignissimos dolore reiciendis dolores repellat aut rem! Iste, nisi nihil. Vero laboriosam nemo saepe, incidunt dolor reiciendis corrupti. Quibusdam officia doloribus distinctio necessitatibus harum hic odit nemo. Ratione, debitis aut eligendi cupiditate esse incidunt quasi possimus? Doloribus velit voluptatem inventore, totam officiis culpa quae commodi?</section>
      <section>Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda laudantium veniam illo qui labore provident sunt ipsum aliquid non ipsa. Repudiandae nisi accusamus assumenda iste iusto quos. Numquam impedit, animi dolor illo at atque facere. Deserunt inventore, ut ea natus fuga, nesciunt doloremque, totam quos amet nihil repellat culpa corporis! In tempore et distinctio doloremque at accusamus deserunt magnam. Libero dignissimos aut architecto tempora at corporis quas commodi praesentium minus, cum voluptate eum, labore nemo deserunt quibusdam rem perferendis tempore optio veniam. Quidem, maiores praesentium delectus eius numquam ipsa quibusdam eaque animi, veritatis consequuntur explicabo molestias, ut natus! Voluptatum excepturi consequuntur, dicta asperiores odio ipsum veniam, omnis quibusdam obcaecati, beatae enim velit incidunt saepe! Doloremque, ex labore? Doloribus ex inventore veniam harum cum quasi ipsam natus, dolorum debitis commodi labore repudiandae quos magnam necessitatibus iusto mollitia consequatur ullam optio dicta dolores! Asperiores quaerat, neque a voluptas aliquam sunt adipisci saepe eius ratione laborum commodi sed dignissimos dolore reiciendis dolores repellat aut rem! Iste, nisi nihil. Vero laboriosam nemo saepe, incidunt dolor reiciendis corrupti. Quibusdam officia doloribus distinctio necessitatibus harum hic odit nemo. Ratione, debitis aut eligendi cupiditate esse incidunt quasi possimus? Doloribus velit voluptatem inventore, totam officiis culpa quae commodi?</section>
    </div>
  </div>;
};

export default LandingPage;